from dataclasses import replace
from datetime import datetime

from backend.constants import SCANNER_GRACE_PERIOD_SECONDS
from backend.context.scanner_context import ScannerContext
from backend.models import RiskLevel, ThreatAlertRecord

_SUPPRESSION_REASON = (
    "Traffic generated by authorized scanner host during active Nmap scan. "
    "Suppressed from threat risk scoring."
)


def apply_scanner_suppression(
    threat_alerts: list[ThreatAlertRecord],
    scanner_context: ScannerContext,
) -> tuple[list[ThreatAlertRecord], list[ThreatAlertRecord]]:
    """
    Split alerts into active and suppressed.
    Alerts are suppressed (not deleted) so the report can still show them
    as authorized activity — keeping the audit trail intact.
    """
    suppression_deadline = scanner_context.scan_end_time + SCANNER_GRACE_PERIOD_SECONDS

    active_alerts: list[ThreatAlertRecord] = []
    suppressed_alerts: list[ThreatAlertRecord] = []

    for alert in threat_alerts:
        if _is_scanner_generated_alert(alert, scanner_context, suppression_deadline):
            suppressed_alerts.append(_tag_as_suppressed(alert))
        else:
            active_alerts.append(alert)

    return active_alerts, suppressed_alerts


def _is_scanner_generated_alert(
    alert: ThreatAlertRecord,
    context: ScannerContext,
    suppression_deadline: float,
) -> bool:
    if alert.source_ip not in context.authorized_scanner_ips:
        return False
    if alert.threat_category not in context.suppressed_categories:
        return False
    alert_epoch = _parse_alert_timestamp(alert.timestamp)
    # If timestamp is unparseable, suppress conservatively — better to
    # over-suppress own traffic than to falsely escalate it.
    if alert_epoch is None:
        return True
    return context.scan_start_time <= alert_epoch <= suppression_deadline


def _parse_alert_timestamp(timestamp_str: str) -> float | None:
    if not timestamp_str:
        return None
    try:
        return datetime.fromisoformat(timestamp_str).timestamp()
    except ValueError:
        return None


def _tag_as_suppressed(alert: ThreatAlertRecord) -> ThreatAlertRecord:
    return replace(
        alert,
        is_suppressed=True,
        suppressed_from_risk_score=True,
        original_risk_level=alert.risk_level,
        risk_level=RiskLevel.LOW,
        false_positive_reason=_SUPPRESSION_REASON,
    )
